// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Edit atom.
public struct EditAtom: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique key for this atom. Must be specified when using advanced
  /// mapping.
  public var key: Swift.String = Swift.String()

  /// List of [Input.key][google.cloud.video.transcoder.v1.Input.key] values
  /// identifying files that should be used in this atom. The listed `inputs`
  /// must have the same timeline.
  ///
  /// [google.cloud.video.transcoder.v1.Input.key]: <doc:Input/key>
  public var inputs: [Swift.String] = []

  /// End time in seconds for the atom, relative to the input file timeline.
  /// When `end_time_offset` is not specified, the `inputs` are used until
  /// the end of the atom.
  public var endTimeOffset: GoogleWKT.WKTDuration? = nil

  /// Start time in seconds for the atom, relative to the input file timeline.
  /// The default is `0s`.
  public var startTimeOffset: GoogleWKT.WKTDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EditAtom`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EditAtom().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let inputs = CodingKeys(stringValue: "inputs")
    static let endTimeOffset = CodingKeys(stringValue: "endTimeOffset")
    static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "inputs",
      "endTimeOffset",
      "startTimeOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .inputs) {
      self.inputs = value
    }
    self.endTimeOffset = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .endTimeOffset)
    self.startTimeOffset = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .startTimeOffset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.inputs, forKey: .inputs)
    try container.encodeIfPresent(self.endTimeOffset, forKey: .endTimeOffset)
    try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.EditAtom"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
