// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Encoding of an input file such as an audio, video, or text track.
/// Elementary streams must be packaged before
/// mapping and sharing between different output formats.
public struct ElementaryStream: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique key for this elementary stream.
  public var key: Swift.String = Swift.String()

  /// Encoding of an audio, video, or text track.
  public var elementaryStream: ElementaryStreamOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ElementaryStream`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ElementaryStream().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let videoStream = CodingKeys(stringValue: "videoStream")
    static let audioStream = CodingKeys(stringValue: "audioStream")
    static let textStream = CodingKeys(stringValue: "textStream")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "videoStream",
      "audioStream",
      "textStream",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }

    var elementaryStream: ElementaryStreamOneOf? = nil
    let elementaryStreamCheckAndSet = {
      if elementaryStream != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'elementaryStream'"))
      }
      elementaryStream = $0
    }
    if let videoStream = try container.decodeIfPresent(VideoStream?.self, forKey: .videoStream) {
      try elementaryStreamCheckAndSet(.videoStream(videoStream))
    }
    if let audioStream = try container.decodeIfPresent(AudioStream?.self, forKey: .audioStream) {
      try elementaryStreamCheckAndSet(.audioStream(audioStream))
    }
    if let textStream = try container.decodeIfPresent(TextStream?.self, forKey: .textStream) {
      try elementaryStreamCheckAndSet(.textStream(textStream))
    }
    self.elementaryStream = elementaryStream
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)

    if let choice = self.elementaryStream {
      switch choice {
      case .videoStream(let value):
        try container.encode(value, forKey: .videoStream)
      case .audioStream(let value):
        try container.encode(value, forKey: .audioStream)
      case .textStream(let value):
        try container.encode(value, forKey: .textStream)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Encoding of an audio, video, or text track.
  public enum ElementaryStreamOneOf: Codable, Equatable, Sendable {
    /// Encoding of a video stream.
    indirect case videoStream(VideoStream?)
    /// Encoding of an audio stream.
    indirect case audioStream(AudioStream?)
    /// Encoding of a text stream. For example, closed captions or subtitles.
    indirect case textStream(TextStream?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.ElementaryStream"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
