// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Input asset.
public struct Input: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// A unique key for this input. Must be specified when using advanced
  /// mapping and edit lists.
  public var key: Swift.String = Swift.String()

  /// URI of the media. Input files must be at least 5 seconds in duration and
  /// stored in Cloud Storage (for example, `gs://bucket/inputs/file.mp4`).
  /// If empty, the value is populated from
  /// [Job.input_uri][google.cloud.video.transcoder.v1.Job.input_uri]. See
  /// [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats).
  ///
  /// [google.cloud.video.transcoder.v1.Job.input_uri]: <doc:Job/inputUri>
  public var uri: Swift.String = Swift.String()

  /// Preprocessing configurations.
  public var preprocessingConfig: PreprocessingConfig? = nil

  /// Optional. Input Attributes.
  public var attributes: InputAttributes? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Input`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Input().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let uri = CodingKeys(stringValue: "uri")
    static let preprocessingConfig = CodingKeys(stringValue: "preprocessingConfig")
    static let attributes = CodingKeys(stringValue: "attributes")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "uri",
      "preprocessingConfig",
      "attributes",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    self.preprocessingConfig = try container.decodeIfPresent(
      PreprocessingConfig.self, forKey: .preprocessingConfig)
    self.attributes = try container.decodeIfPresent(InputAttributes.self, forKey: .attributes)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.uri, forKey: .uri)
    try container.encodeIfPresent(self.preprocessingConfig, forKey: .preprocessingConfig)
    try container.encodeIfPresent(self.attributes, forKey: .attributes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Input"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
