// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Transcoding job resource.
public struct Job: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the job.
  /// Format: `projects/{project_number}/locations/{location}/jobs/{job}`
  public var name: Swift.String = Swift.String()

  /// Input only. Specify the `input_uri` to populate empty `uri` fields in each
  /// element of `Job.config.inputs` or `JobTemplate.config.inputs` when using
  /// template. URI of the media. Input files must be at least 5 seconds in
  /// duration and stored in Cloud Storage (for example,
  /// `gs://bucket/inputs/file.mp4`). See [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats).
  public var inputUri: Swift.String = Swift.String()

  /// Input only. Specify the `output_uri` to populate an empty
  /// `Job.config.output.uri` or `JobTemplate.config.output.uri` when using
  /// template. URI for the output file(s). For example,
  /// `gs://my-bucket/outputs/`. See [Supported input and output
  /// formats](https://cloud.google.com/transcoder/docs/concepts/supported-input-and-output-formats).
  public var outputUri: Swift.String = Swift.String()

  /// Output only. The current state of the job.
  public var state: Job.ProcessingState = Job.ProcessingState()

  /// Output only. The time the job was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time the transcoding started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time the transcoding finished.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Job time to live value in days, which will be effective after job
  /// completion. Job should be deleted automatically after the given TTL. Enter
  /// a value between 1 and 90. The default is 30.
  public var ttlAfterCompletionDays: Swift.Int32 = Swift.Int32()

  /// The labels associated with this job. You can use these to organize and
  /// group your jobs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. An error object that describes the reason for the failure.
  /// This property is always present when
  /// [ProcessingState][google.cloud.video.transcoder.v1.Job.ProcessingState] is
  /// `FAILED`.
  ///
  /// [google.cloud.video.transcoder.v1.Job.ProcessingState]: <doc:Job/ProcessingState>
  public var error: GoogleRpc.Status? = nil

  /// The processing mode of the job.
  /// The default is `PROCESSING_MODE_INTERACTIVE`.
  public var mode: Job.ProcessingMode = Job.ProcessingMode()

  /// The processing priority of a batch job.
  /// This field can only be set for batch mode jobs. The default value is 0.
  /// This value cannot be negative. Higher values correspond to higher
  /// priorities for the job.
  public var batchModePriority: Swift.Int32 = Swift.Int32()

  /// Optional. The optimization strategy of the job. The default is
  /// `AUTODETECT`.
  public var optimization: Job.OptimizationStrategy = Job.OptimizationStrategy()

  /// Optional. Insert silence and duplicate frames when timestamp gaps are
  /// detected in a given stream.
  public var fillContentGaps: Swift.Bool = Swift.Bool()

  /// Specify the config for the transcoding job. If you don't specify the
  /// `job_config`, the API selects `templateId`; this template ID is set to
  /// `preset/web-hd` by default. When you use a `template_id` to create a job,
  /// the `Job.config` is populated by the `JobTemplate.config`.<br>
  public var jobConfig: OneOf_JobConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let inputUri = CodingKeys(stringValue: "inputUri")
    static let outputUri = CodingKeys(stringValue: "outputUri")
    static let templateId = CodingKeys(stringValue: "templateId")
    static let config = CodingKeys(stringValue: "config")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let ttlAfterCompletionDays = CodingKeys(stringValue: "ttlAfterCompletionDays")
    static let labels = CodingKeys(stringValue: "labels")
    static let error = CodingKeys(stringValue: "error")
    static let mode = CodingKeys(stringValue: "mode")
    static let batchModePriority = CodingKeys(stringValue: "batchModePriority")
    static let optimization = CodingKeys(stringValue: "optimization")
    static let fillContentGaps = CodingKeys(stringValue: "fillContentGaps")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "inputUri",
      "outputUri",
      "templateId",
      "config",
      "state",
      "createTime",
      "startTime",
      "endTime",
      "ttlAfterCompletionDays",
      "labels",
      "error",
      "mode",
      "batchModePriority",
      "optimization",
      "fillContentGaps",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputUri) {
      self.inputUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
      self.outputUri = value
    }
    if let value = try container.decodeIfPresent(Job.ProcessingState.self, forKey: .state) {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .ttlAfterCompletionDays)
    {
      self.ttlAfterCompletionDays = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    if let value = try container.decodeIfPresent(Job.ProcessingMode.self, forKey: .mode) {
      self.mode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .batchModePriority) {
      self.batchModePriority = value
    }
    if let value = try container.decodeIfPresent(
      Job.OptimizationStrategy.self, forKey: .optimization)
    {
      self.optimization = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .fillContentGaps) {
      self.fillContentGaps = value
    }

    var jobConfig: OneOf_JobConfig? = nil
    let jobConfigCheckAndSet = {
      if jobConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'jobConfig'"))
      }
      jobConfig = $0
    }
    if let templateId = try container.decodeIfPresent(Swift.String.self, forKey: .templateId) {
      try jobConfigCheckAndSet(.templateId(templateId))
    }
    if let config = try container.decodeIfPresent(JobConfig?.self, forKey: .config) {
      try jobConfigCheckAndSet(.config(config))
    }
    self.jobConfig = jobConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.inputUri, forKey: .inputUri)
    try container.encode(self.outputUri, forKey: .outputUri)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.ttlAfterCompletionDays, forKey: .ttlAfterCompletionDays)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encode(self.mode, forKey: .mode)
    try container.encode(self.batchModePriority, forKey: .batchModePriority)
    try container.encode(self.optimization, forKey: .optimization)
    try container.encode(self.fillContentGaps, forKey: .fillContentGaps)

    if let choice = self.jobConfig {
      switch choice {
      case .templateId(let value):
        try container.encode(value, forKey: .templateId)
      case .config(let value):
        try container.encode(value, forKey: .config)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The current state of the job.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ProcessingState: Codable, Equatable, Hashable, Sendable {
    /// The processing state is not specified.
    case unspecified
    /// The job is enqueued and will be picked up for processing soon.
    case pending
    /// The job is being processed.
    case running
    /// The job has been completed successfully.
    case succeeded
    /// The job has failed. For additional information, see
    /// [Troubleshooting](https://cloud.google.com/transcoder/docs/troubleshooting).
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .running: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROCESSING_STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProcessingState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROCESSING_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProcessingState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .running
      case 3: self = .succeeded
      case 4: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROCESSING_STATE_UNSPECIFIED")
      case .pending: return try container.encode("PENDING")
      case .running: return try container.encode("RUNNING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The processing mode of the job.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ProcessingMode: Codable, Equatable, Hashable, Sendable {
    /// The job processing mode is not specified.
    case unspecified
    /// The job processing mode is interactive mode.
    /// Interactive job will either be ran or rejected if quota does not allow
    /// for it.
    case interactive
    /// The job processing mode is batch mode.
    /// Batch mode allows queuing of jobs.
    case batch
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .interactive: return 1
      case .batch: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PROCESSING_MODE_UNSPECIFIED"
      case .interactive: return "PROCESSING_MODE_INTERACTIVE"
      case .batch: return "PROCESSING_MODE_BATCH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProcessingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PROCESSING_MODE_UNSPECIFIED": self = .unspecified
      case "PROCESSING_MODE_INTERACTIVE": self = .interactive
      case "PROCESSING_MODE_BATCH": self = .batch
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ProcessingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .interactive
      case 2: self = .batch
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PROCESSING_MODE_UNSPECIFIED")
      case .interactive: return try container.encode("PROCESSING_MODE_INTERACTIVE")
      case .batch: return try container.encode("PROCESSING_MODE_BATCH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The optimization strategy of the job. The default is `AUTODETECT`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum OptimizationStrategy: Codable, Equatable, Hashable, Sendable {
    /// The optimization strategy is not specified.
    case unspecified
    /// Prioritize job processing speed.
    case autodetect
    /// Disable all optimizations.
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .autodetect: return 1
      case .disabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "OPTIMIZATION_STRATEGY_UNSPECIFIED"
      case .autodetect: return "AUTODETECT"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:OptimizationStrategy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "OPTIMIZATION_STRATEGY_UNSPECIFIED": self = .unspecified
      case "AUTODETECT": self = .autodetect
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:OptimizationStrategy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .autodetect
      case 2: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("OPTIMIZATION_STRATEGY_UNSPECIFIED")
      case .autodetect: return try container.encode("AUTODETECT")
      case .disabled: return try container.encode("DISABLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specify the config for the transcoding job. If you don't specify the
  /// `job_config`, the API selects `templateId`; this template ID is set to
  /// `preset/web-hd` by default. When you use a `template_id` to create a job,
  /// the `Job.config` is populated by the `JobTemplate.config`.<br>
  public enum OneOf_JobConfig: Codable, Equatable, Sendable {
    /// Input only. Specify the `template_id` to use for populating `Job.config`.
    /// The default is `preset/web-hd`, which is the only supported preset.
    ///
    /// User defined JobTemplate: `{job_template_id}`
    case templateId(Swift.String)
    /// The configuration for this job.
    indirect case config(JobConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Job"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
