// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Job configuration
public struct JobConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// List of input assets stored in Cloud Storage.
  public var inputs: [Input] = []

  /// List of edit atoms. Defines the ultimate timeline of the resulting
  /// file or manifest.
  public var editList: [EditAtom] = []

  /// List of elementary streams.
  public var elementaryStreams: [ElementaryStream] = []

  /// List of multiplexing settings for output streams.
  public var muxStreams: [MuxStream] = []

  /// List of output manifests.
  public var manifests: [Manifest] = []

  /// Output configuration.
  public var output: Output? = nil

  /// List of ad breaks. Specifies where to insert ad break tags in the output
  /// manifests.
  public var adBreaks: [AdBreak] = []

  /// Destination on Pub/Sub.
  public var pubsubDestination: PubsubDestination? = nil

  /// List of output sprite sheets.
  /// Spritesheets require at least one VideoStream in the Jobconfig.
  public var spriteSheets: [SpriteSheet] = []

  /// List of overlays on the output video, in descending Z-order.
  public var overlays: [Overlay] = []

  /// List of encryption configurations for the content.
  /// Each configuration has an ID. Specify this ID in the
  /// [MuxStream.encryption_id][google.cloud.video.transcoder.v1.MuxStream.encryption_id]
  /// field to indicate the configuration to use for that `MuxStream` output.
  ///
  /// [google.cloud.video.transcoder.v1.MuxStream.encryption_id]: <doc:MuxStream/encryptionId>
  public var encryptions: [Encryption] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `JobConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = JobConfig().with { $0.inputs = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputs = CodingKeys(stringValue: "inputs")
    static let editList = CodingKeys(stringValue: "editList")
    static let elementaryStreams = CodingKeys(stringValue: "elementaryStreams")
    static let muxStreams = CodingKeys(stringValue: "muxStreams")
    static let manifests = CodingKeys(stringValue: "manifests")
    static let output = CodingKeys(stringValue: "output")
    static let adBreaks = CodingKeys(stringValue: "adBreaks")
    static let pubsubDestination = CodingKeys(stringValue: "pubsubDestination")
    static let spriteSheets = CodingKeys(stringValue: "spriteSheets")
    static let overlays = CodingKeys(stringValue: "overlays")
    static let encryptions = CodingKeys(stringValue: "encryptions")

    static let _knownKeys: Set<Swift.String> = [
      "inputs",
      "editList",
      "elementaryStreams",
      "muxStreams",
      "manifests",
      "output",
      "adBreaks",
      "pubsubDestination",
      "spriteSheets",
      "overlays",
      "encryptions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Input].self, forKey: .inputs) {
      self.inputs = value
    }
    if let value = try container.decodeIfPresent([EditAtom].self, forKey: .editList) {
      self.editList = value
    }
    if let value = try container.decodeIfPresent(
      [ElementaryStream].self, forKey: .elementaryStreams)
    {
      self.elementaryStreams = value
    }
    if let value = try container.decodeIfPresent([MuxStream].self, forKey: .muxStreams) {
      self.muxStreams = value
    }
    if let value = try container.decodeIfPresent([Manifest].self, forKey: .manifests) {
      self.manifests = value
    }
    self.output = try container.decodeIfPresent(Output.self, forKey: .output)
    if let value = try container.decodeIfPresent([AdBreak].self, forKey: .adBreaks) {
      self.adBreaks = value
    }
    self.pubsubDestination = try container.decodeIfPresent(
      PubsubDestination.self, forKey: .pubsubDestination)
    if let value = try container.decodeIfPresent([SpriteSheet].self, forKey: .spriteSheets) {
      self.spriteSheets = value
    }
    if let value = try container.decodeIfPresent([Overlay].self, forKey: .overlays) {
      self.overlays = value
    }
    if let value = try container.decodeIfPresent([Encryption].self, forKey: .encryptions) {
      self.encryptions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputs, forKey: .inputs)
    try container.encode(self.editList, forKey: .editList)
    try container.encode(self.elementaryStreams, forKey: .elementaryStreams)
    try container.encode(self.muxStreams, forKey: .muxStreams)
    try container.encode(self.manifests, forKey: .manifests)
    try container.encodeIfPresent(self.output, forKey: .output)
    try container.encode(self.adBreaks, forKey: .adBreaks)
    try container.encodeIfPresent(self.pubsubDestination, forKey: .pubsubDestination)
    try container.encode(self.spriteSheets, forKey: .spriteSheets)
    try container.encode(self.overlays, forKey: .overlays)
    try container.encode(self.encryptions, forKey: .encryptions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.JobConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
