// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Manifest configuration.
public struct Manifest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the generated file. The default is `manifest` with the
  /// extension suffix corresponding to the
  /// [Manifest.type][google.cloud.video.transcoder.v1.Manifest.type].
  ///
  /// [google.cloud.video.transcoder.v1.Manifest.type]: <doc:Manifest/type>
  public var fileName: Swift.String = Swift.String()

  /// Required. Type of the manifest.
  public var type: Manifest.ManifestType = Manifest.ManifestType()

  /// Required. List of user supplied
  /// [MuxStream.key][google.cloud.video.transcoder.v1.MuxStream.key] values that
  /// should appear in this manifest.
  ///
  /// When [Manifest.type][google.cloud.video.transcoder.v1.Manifest.type] is
  /// `HLS`, a media manifest with name
  /// [MuxStream.key][google.cloud.video.transcoder.v1.MuxStream.key] and `.m3u8`
  /// extension is generated for each element in this list.
  ///
  /// [google.cloud.video.transcoder.v1.Manifest.type]: <doc:Manifest/type>
  /// [google.cloud.video.transcoder.v1.MuxStream.key]: <doc:MuxStream/key>
  public var muxStreams: [Swift.String] = []

  /// Specifies the manifest configuration.
  public var manifestConfig: ManifestConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Manifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Manifest().with { $0.fileName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fileName = CodingKeys(stringValue: "fileName")
    static let type = CodingKeys(stringValue: "type")
    static let muxStreams = CodingKeys(stringValue: "muxStreams")
    static let dash = CodingKeys(stringValue: "dash")

    static let _knownKeys: Set<Swift.String> = [
      "fileName",
      "type",
      "muxStreams",
      "dash",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fileName) {
      self.fileName = value
    }
    if let value = try container.decodeIfPresent(Manifest.ManifestType.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .muxStreams) {
      self.muxStreams = value
    }

    var manifestConfig: ManifestConfigOneOf? = nil
    let manifestConfigCheckAndSet = {
      if manifestConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'manifestConfig'"))
      }
      manifestConfig = $0
    }
    if let dash = try container.decodeIfPresent(Manifest.DashConfig?.self, forKey: .dash) {
      try manifestConfigCheckAndSet(.dash(dash))
    }
    self.manifestConfig = manifestConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fileName, forKey: .fileName)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.muxStreams, forKey: .muxStreams)

    if let choice = self.manifestConfig {
      switch choice {
      case .dash(let value):
        try container.encode(value, forKey: .dash)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// `DASH` manifest configuration.
  public struct DashConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The segment reference scheme for a `DASH` manifest. The default is
    /// `SEGMENT_LIST`.
    public var segmentReferenceScheme: Manifest.DashConfig.SegmentReferenceScheme = Manifest
      .DashConfig.SegmentReferenceScheme()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DashConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DashConfig().with { $0.segmentReferenceScheme = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let segmentReferenceScheme = CodingKeys(stringValue: "segmentReferenceScheme")

      static let _knownKeys: Set<Swift.String> = [
        "segmentReferenceScheme"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Manifest.DashConfig.SegmentReferenceScheme.self, forKey: .segmentReferenceScheme)
      {
        self.segmentReferenceScheme = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.segmentReferenceScheme, forKey: .segmentReferenceScheme)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The segment reference scheme for a `DASH` manifest.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SegmentReferenceScheme: Codable, Equatable, Hashable, Sendable {
      /// The segment reference scheme is not specified.
      case unspecified
      /// Explicitly lists the URLs of media files for each segment. For example,
      /// if
      /// [SegmentSettings.individual_segments][google.cloud.video.transcoder.v1.SegmentSettings.individual_segments]
      /// is `true`, then the manifest contains fields similar to the following:
      /// ```xml
      /// <Initialization sourceURL="my-hd-stream-init.m4s"/>
      ///   <SegmentList presentationTimeOffset="0" duration="1000"
      ///   timescale="10000">
      ///     <SegmentURL media="hd-stream0000000000.m4s"/>
      ///     <SegmentURL media="hd-stream0000000001.m4s"/>
      ///     ...
      /// ```
      ///
      /// [google.cloud.video.transcoder.v1.SegmentSettings.individual_segments]: <doc:SegmentSettings/individualSegments>
      case segmentList
      /// [SegmentSettings.individual_segments][google.cloud.video.transcoder.v1.SegmentSettings.individual_segments]
      /// must be set to `true` to use this segment reference scheme. Uses the
      /// DASH specification
      /// `<SegmentTemplate>` tag to determine the URLs of media files for each
      /// segment. For example:
      /// ```xml
      /// <SegmentTemplate presentationTimeOffset="0" timescale="10000"
      ///       initialization="my-hd-stream-init.m4s"
      ///       media="hd-stream$Number%010d$.m4s" startNumber="0">
      ///   ...
      /// ```
      ///
      /// [google.cloud.video.transcoder.v1.SegmentSettings.individual_segments]: <doc:SegmentSettings/individualSegments>
      case segmentTemplateNumber
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .segmentList: return 1
        case .segmentTemplateNumber: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SEGMENT_REFERENCE_SCHEME_UNSPECIFIED"
        case .segmentList: return "SEGMENT_LIST"
        case .segmentTemplateNumber: return "SEGMENT_TEMPLATE_NUMBER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SegmentReferenceScheme/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SEGMENT_REFERENCE_SCHEME_UNSPECIFIED": self = .unspecified
        case "SEGMENT_LIST": self = .segmentList
        case "SEGMENT_TEMPLATE_NUMBER": self = .segmentTemplateNumber
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SegmentReferenceScheme/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .segmentList
        case 2: self = .segmentTemplateNumber
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SEGMENT_REFERENCE_SCHEME_UNSPECIFIED")
        case .segmentList: return try container.encode("SEGMENT_LIST")
        case .segmentTemplateNumber: return try container.encode("SEGMENT_TEMPLATE_NUMBER")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Manifest.DashConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The manifest type, which corresponds to the adaptive streaming format used.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ManifestType: Codable, Equatable, Hashable, Sendable {
    /// The manifest type is not specified.
    case unspecified
    /// Create an HLS manifest. The corresponding file extension is `.m3u8`.
    case hls
    /// Create an MPEG-DASH manifest. The corresponding file extension is `.mpd`.
    case dash
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hls: return 1
      case .dash: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MANIFEST_TYPE_UNSPECIFIED"
      case .hls: return "HLS"
      case .dash: return "DASH"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ManifestType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MANIFEST_TYPE_UNSPECIFIED": self = .unspecified
      case "HLS": self = .hls
      case "DASH": self = .dash
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ManifestType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hls
      case 2: self = .dash
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("MANIFEST_TYPE_UNSPECIFIED")
      case .hls: return try container.encode("HLS")
      case .dash: return try container.encode("DASH")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies the manifest configuration.
  public enum ManifestConfigOneOf: Codable, Equatable, Sendable {
    /// `DASH` manifest configuration.
    indirect case dash(Manifest.DashConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Manifest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
