// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Overlay configuration.
public struct Overlay: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Image overlay.
  public var image: Overlay.Image? = nil

  /// List of animations. The list should be chronological, without any time
  /// overlap.
  public var animations: [Overlay.Animation] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Overlay`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Overlay().with { $0.image = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let image = CodingKeys(stringValue: "image")
    static let animations = CodingKeys(stringValue: "animations")

    static let _knownKeys: Set<Swift.String> = [
      "image",
      "animations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.image = try container.decodeIfPresent(Overlay.Image.self, forKey: .image)
    if let value = try container.decodeIfPresent([Overlay.Animation].self, forKey: .animations) {
      self.animations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.image, forKey: .image)
    try container.encode(self.animations, forKey: .animations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// 2D normalized coordinates. Default: `{0.0, 0.0}`
  public struct NormalizedCoordinate: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Normalized x coordinate.
    public var x: Swift.Double = Swift.Double()

    /// Normalized y coordinate.
    public var y: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NormalizedCoordinate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NormalizedCoordinate().with { $0.x = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let x = CodingKeys(stringValue: "x")
      static let y = CodingKeys(stringValue: "y")

      static let _knownKeys: Set<Swift.String> = [
        "x",
        "y",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .x) {
        self.x = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .y) {
        self.y = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.x, forKey: .x)
      try container.encode(self.y, forKey: .y)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.NormalizedCoordinate"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Overlaid image.
  public struct Image: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. URI of the image in Cloud Storage. For example,
    /// `gs://bucket/inputs/image.png`. Only PNG and JPEG images are supported.
    public var uri: Swift.String = Swift.String()

    /// Normalized image resolution, based on output video resolution. Valid
    /// values: `0.0`–`1.0`. To respect the original image aspect ratio, set
    /// either `x` or `y` to `0.0`. To use the original image resolution, set
    /// both `x` and `y` to `0.0`.
    public var resolution: Overlay.NormalizedCoordinate? = nil

    /// Target image opacity. Valid values are from  `1.0` (solid, default) to
    /// `0.0` (transparent), exclusive. Set this to a value greater than `0.0`.
    public var alpha: Swift.Double = Swift.Double()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Image`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Image().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uri = CodingKeys(stringValue: "uri")
      static let resolution = CodingKeys(stringValue: "resolution")
      static let alpha = CodingKeys(stringValue: "alpha")

      static let _knownKeys: Set<Swift.String> = [
        "uri",
        "resolution",
        "alpha",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      self.resolution = try container.decodeIfPresent(
        Overlay.NormalizedCoordinate.self, forKey: .resolution)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .alpha) {
        self.alpha = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uri, forKey: .uri)
      try container.encodeIfPresent(self.resolution, forKey: .resolution)
      try container.encode(self.alpha, forKey: .alpha)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.Image"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Display static overlay object.
  public struct AnimationStatic: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Normalized coordinates based on output video resolution. Valid
    /// values: `0.0`–`1.0`. `xy` is the upper-left coordinate of the overlay
    /// object. For example, use the x and y coordinates {0,0} to position the
    /// top-left corner of the overlay animation in the top-left corner of the
    /// output video.
    public var xy: Overlay.NormalizedCoordinate? = nil

    /// The time to start displaying the overlay object, in seconds. Default: 0
    public var startTimeOffset: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AnimationStatic`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnimationStatic().with { $0.xy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let xy = CodingKeys(stringValue: "xy")
      static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")

      static let _knownKeys: Set<Swift.String> = [
        "xy",
        "startTimeOffset",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.xy = try container.decodeIfPresent(Overlay.NormalizedCoordinate.self, forKey: .xy)
      self.startTimeOffset = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .startTimeOffset)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.xy, forKey: .xy)
      try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.AnimationStatic"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Display overlay object with fade animation.
  public struct AnimationFade: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Type of fade animation: `FADE_IN` or `FADE_OUT`.
    public var fadeType: Overlay.FadeType = Overlay.FadeType()

    /// Normalized coordinates based on output video resolution. Valid
    /// values: `0.0`–`1.0`. `xy` is the upper-left coordinate of the overlay
    /// object. For example, use the x and y coordinates {0,0} to position the
    /// top-left corner of the overlay animation in the top-left corner of the
    /// output video.
    public var xy: Overlay.NormalizedCoordinate? = nil

    /// The time to start the fade animation, in seconds. Default: 0
    public var startTimeOffset: GoogleWKT.WKTDuration? = nil

    /// The time to end the fade animation, in seconds. Default:
    /// `start_time_offset` + 1s
    public var endTimeOffset: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AnimationFade`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnimationFade().with { $0.fadeType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fadeType = CodingKeys(stringValue: "fadeType")
      static let xy = CodingKeys(stringValue: "xy")
      static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")
      static let endTimeOffset = CodingKeys(stringValue: "endTimeOffset")

      static let _knownKeys: Set<Swift.String> = [
        "fadeType",
        "xy",
        "startTimeOffset",
        "endTimeOffset",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Overlay.FadeType.self, forKey: .fadeType) {
        self.fadeType = value
      }
      self.xy = try container.decodeIfPresent(Overlay.NormalizedCoordinate.self, forKey: .xy)
      self.startTimeOffset = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .startTimeOffset)
      self.endTimeOffset = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .endTimeOffset)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.fadeType, forKey: .fadeType)
      try container.encodeIfPresent(self.xy, forKey: .xy)
      try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
      try container.encodeIfPresent(self.endTimeOffset, forKey: .endTimeOffset)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.AnimationFade"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// End previous overlay animation from the video. Without `AnimationEnd`, the
  /// overlay object will keep the state of previous animation until the end of
  /// the video.
  public struct AnimationEnd: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The time to end overlay object, in seconds. Default: 0
    public var startTimeOffset: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AnimationEnd`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnimationEnd().with { $0.startTimeOffset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")

      static let _knownKeys: Set<Swift.String> = [
        "startTimeOffset"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.startTimeOffset = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .startTimeOffset)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.AnimationEnd"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Animation types.
  public struct Animation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Animations can be static or fade, or they can end the previous animation.
    public var animationType: AnimationTypeOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Animation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Animation().with { $0.animationStatic = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let animationStatic = CodingKeys(stringValue: "animationStatic")
      static let animationFade = CodingKeys(stringValue: "animationFade")
      static let animationEnd = CodingKeys(stringValue: "animationEnd")

      static let _knownKeys: Set<Swift.String> = [
        "animationStatic",
        "animationFade",
        "animationEnd",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var animationType: AnimationTypeOneOf? = nil
      let animationTypeCheckAndSet = {
        if animationType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'animationType'"))
        }
        animationType = $0
      }
      if let animationStatic = try container.decodeIfPresent(
        Overlay.AnimationStatic?.self, forKey: .animationStatic)
      {
        try animationTypeCheckAndSet(.animationStatic(animationStatic))
      }
      if let animationFade = try container.decodeIfPresent(
        Overlay.AnimationFade?.self, forKey: .animationFade)
      {
        try animationTypeCheckAndSet(.animationFade(animationFade))
      }
      if let animationEnd = try container.decodeIfPresent(
        Overlay.AnimationEnd?.self, forKey: .animationEnd)
      {
        try animationTypeCheckAndSet(.animationEnd(animationEnd))
      }
      self.animationType = animationType
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.animationType {
        switch choice {
        case .animationStatic(let value):
          try container.encode(value, forKey: .animationStatic)
        case .animationFade(let value):
          try container.encode(value, forKey: .animationFade)
        case .animationEnd(let value):
          try container.encode(value, forKey: .animationEnd)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Animations can be static or fade, or they can end the previous animation.
    public enum AnimationTypeOneOf: Codable, Equatable, Sendable {
      /// Display static overlay object.
      indirect case animationStatic(Overlay.AnimationStatic?)
      /// Display overlay object with fade animation.
      indirect case animationFade(Overlay.AnimationFade?)
      /// End previous animation.
      indirect case animationEnd(Overlay.AnimationEnd?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay.Animation"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Fade type for the overlay: `FADE_IN` or `FADE_OUT`.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum FadeType: Codable, Equatable, Hashable, Sendable {
    /// The fade type is not specified.
    case unspecified
    /// Fade the overlay object into view.
    case fadeIn
    /// Fade the overlay object out of view.
    case fadeOut
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .fadeIn: return 1
      case .fadeOut: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FADE_TYPE_UNSPECIFIED"
      case .fadeIn: return "FADE_IN"
      case .fadeOut: return "FADE_OUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FadeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FADE_TYPE_UNSPECIFIED": self = .unspecified
      case "FADE_IN": self = .fadeIn
      case "FADE_OUT": self = .fadeOut
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FadeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .fadeIn
      case 2: self = .fadeOut
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FADE_TYPE_UNSPECIFIED")
      case .fadeIn: return try container.encode("FADE_IN")
      case .fadeOut: return try container.encode("FADE_OUT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.Overlay"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
