// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Segment settings for `ts`, `fmp4` and `vtt`.
public struct SegmentSettings: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Duration of the segments in seconds. The default is `6.0s`. Note that
  /// `segmentDuration` must be greater than or equal to
  /// [`gopDuration`](#videostream), and `segmentDuration` must be divisible by
  /// [`gopDuration`](#videostream).
  public var segmentDuration: GoogleWKT.WKTDuration? = nil

  /// Required. Create an individual segment file. The default is `false`.
  public var individualSegments: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SegmentSettings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SegmentSettings().with { $0.segmentDuration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let segmentDuration = CodingKeys(stringValue: "segmentDuration")
    static let individualSegments = CodingKeys(stringValue: "individualSegments")

    static let _knownKeys: Set<Swift.String> = [
      "segmentDuration",
      "individualSegments",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.segmentDuration = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .segmentDuration)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .individualSegments) {
      self.individualSegments = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.segmentDuration, forKey: .segmentDuration)
    try container.encode(self.individualSegments, forKey: .individualSegments)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.SegmentSettings"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
