// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Track definition for the input asset.
public struct TrackDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The input track.
  public var inputTrack: Swift.Int32? = nil

  /// Optional. A list of languages spoken in the input asset, represented by a
  /// BCP 47 language code, such as "en-US" or "sr-Latn". For more information,
  /// see https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  public var languages: [Swift.String] = []

  /// Optional. Whether to automatically detect the languages present in the
  /// track. If true, the system will attempt to identify all the languages
  /// present in the track and populate the languages field.
  public var detectLanguages: Swift.Bool = Swift.Bool()

  /// Output only. A list of languages detected in the input asset, represented
  /// by a BCP 47 language code, such as "en-US" or "sr-Latn". For more
  /// information, see
  /// https://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
  /// This field is only populated if the detect_languages field is set to true.
  public var detectedLanguages: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TrackDefinition`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrackDefinition().with { $0.inputTrack = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputTrack = CodingKeys(stringValue: "inputTrack")
    static let languages = CodingKeys(stringValue: "languages")
    static let detectLanguages = CodingKeys(stringValue: "detectLanguages")
    static let detectedLanguages = CodingKeys(stringValue: "detectedLanguages")

    static let _knownKeys: Set<Swift.String> = [
      "inputTrack",
      "languages",
      "detectLanguages",
      "detectedLanguages",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.inputTrack = try container.decodeIfPresent(Swift.Int32.self, forKey: .inputTrack)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languages) {
      self.languages = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .detectLanguages) {
      self.detectLanguages = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .detectedLanguages) {
      self.detectedLanguages = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.inputTrack, forKey: .inputTrack)
    try container.encode(self.languages, forKey: .languages)
    try container.encode(self.detectLanguages, forKey: .detectLanguages)
    try container.encode(self.detectedLanguages, forKey: .detectedLanguages)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.transcoder.v1.TrackDefinition"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
