// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleGax

/// Using the Transcoder API, you can queue asynchronous jobs for transcoding
/// media into various output formats. Output formats may include different
/// streaming standards such as HTTP Live Streaming (HLS) and Dynamic Adaptive
/// Streaming over HTTP (DASH). You can also customize jobs using advanced
/// features such as Digital Rights Management (DRM), audio equalization, content
/// concatenation, and digital ad-stitch ready content generation.
///
/// @Snippet(path: "TranscoderServiceQuickstart")
public final class TranscoderServiceClient: Clients.TranscoderServiceProtocol, Sendable {
  let inner: any Clients.TranscoderServiceStub

  /// Creates a new `TranscoderServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.TranscoderServiceStub = try Clients.TranscoderServiceTransport(options)
    inner = Clients.TranscoderServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TranscoderServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a job in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_CreateJob")
  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    try await self.inner.createJob(request: request, options: options)
  }

  /// Lists jobs in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// Returns the job data.
  ///
  /// @Snippet(path: "TranscoderService_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Deletes a job.
  ///
  /// @Snippet(path: "TranscoderService_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Creates a job template in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_CreateJobTemplate")
  public func createJobTemplate(
    request: CreateJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    try await self.inner.createJobTemplate(request: request, options: options)
  }

  /// Lists job templates in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_ListJobTemplates")
  public func listJobTemplates(
    request: ListJobTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse {
    try await self.inner.listJobTemplates(request: request, options: options)
  }

  /// Returns the job template data.
  ///
  /// @Snippet(path: "TranscoderService_GetJobTemplate")
  public func getJobTemplate(
    request: GetJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    try await self.inner.getJobTemplate(request: request, options: options)
  }

  /// Deletes a job template.
  ///
  /// @Snippet(path: "TranscoderService_DeleteJobTemplate")
  public func deleteJobTemplate(
    request: DeleteJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJobTemplate(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TranscoderServiceClient`.
  ///
  /// To mock `TranscoderServiceClient` change your functions to receive
  /// `some TranscoderServiceProtocol` or `any TranscoderServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TranscoderServiceProtocol: Sendable {
    /// See `TranscoderServiceClient.createJob`.
    func createJob(
      request: CreateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job

    /// See `TranscoderServiceClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse

    /// See `TranscoderServiceClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.Job

    /// See `TranscoderServiceClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `TranscoderServiceClient.createJobTemplate`.
    func createJobTemplate(
      request: CreateJobTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate

    /// See `TranscoderServiceClient.listJobTemplates`.
    func listJobTemplates(
      request: ListJobTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse

    /// See `TranscoderServiceClient.getJobTemplate`.
    func getJobTemplate(
      request: GetJobTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate

    /// See `TranscoderServiceClient.deleteJobTemplate`.
    func deleteJobTemplate(
      request: DeleteJobTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.TranscoderServiceProtocol {
  public func createJob(request: CreateJobRequest) async throws -> GoogleCloudVideoTranscoderV1.Job
  {
    try await self.createJob(request: request, options: .init())
  }

  public func createJob(
    request: CreateJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createJob(
    parent: Swift.String,
    job: Job?,
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    let request = CreateJobRequest().with {
      $0.parent = parent
      $0.job = job
    }
    return try await self.createJob(request: request)
  }

  public func listJobs(request: ListJobsRequest) async throws
    -> GoogleCloudVideoTranscoderV1.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listJobsByItems(
    request: ListJobsRequest
  ) -> any AsyncSequence<Job, Swift.Error> & Sendable {
    self.listJobsByItems(request: request, options: .init())
  }

  /// Lists jobs in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_ListJobs")
  public func listJobsByItems(
    request: ListJobsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Job, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudVideoTranscoderV1.ListJobsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Job, Swift.Error> & Sendable {
    let request = ListJobsRequest().with {
      $0.parent = parent
    }
    return self.listJobsByItems(request: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudVideoTranscoderV1.Job {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getJob(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoTranscoderV1.Job {
    let request = GetJobRequest().with {
      $0.name = name
    }
    return try await self.getJob(request: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteJob(
    name: Swift.String,
  ) async throws {
    let request = DeleteJobRequest().with {
      $0.name = name
    }
    try await self.deleteJob(request: request)
  }

  public func createJobTemplate(request: CreateJobTemplateRequest) async throws
    -> GoogleCloudVideoTranscoderV1.JobTemplate
  {
    try await self.createJobTemplate(request: request, options: .init())
  }

  public func createJobTemplate(
    request: CreateJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createJobTemplate(
    parent: Swift.String,
    jobTemplate: JobTemplate?,
    jobTemplateId: Swift.String,
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    let request = CreateJobTemplateRequest().with {
      $0.parent = parent
      $0.jobTemplate = jobTemplate
      $0.jobTemplateId = jobTemplateId
    }
    return try await self.createJobTemplate(request: request)
  }

  public func listJobTemplates(request: ListJobTemplatesRequest) async throws
    -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse
  {
    try await self.listJobTemplates(request: request, options: .init())
  }

  public func listJobTemplates(
    request: ListJobTemplatesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listJobTemplatesByItems(
    request: ListJobTemplatesRequest
  ) -> any AsyncSequence<JobTemplate, Swift.Error> & Sendable {
    self.listJobTemplatesByItems(request: request, options: .init())
  }

  /// Lists job templates in the specified region.
  ///
  /// @Snippet(path: "TranscoderService_ListJobTemplates")
  public func listJobTemplatesByItems(
    request: ListJobTemplatesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<JobTemplate, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudVideoTranscoderV1.ListJobTemplatesResponse in
      var request = request
      request.pageToken = token
      return try await self.listJobTemplates(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobTemplatesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<JobTemplate, Swift.Error> & Sendable {
    let request = ListJobTemplatesRequest().with {
      $0.parent = parent
    }
    return self.listJobTemplatesByItems(request: request)
  }

  public func getJobTemplate(request: GetJobTemplateRequest) async throws
    -> GoogleCloudVideoTranscoderV1.JobTemplate
  {
    try await self.getJobTemplate(request: request, options: .init())
  }

  public func getJobTemplate(
    request: GetJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getJobTemplate(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoTranscoderV1.JobTemplate {
    let request = GetJobTemplateRequest().with {
      $0.name = name
    }
    return try await self.getJobTemplate(request: request)
  }

  public func deleteJobTemplate(request: DeleteJobTemplateRequest) async throws {
    try await self.deleteJobTemplate(request: request, options: .init())
  }

  public func deleteJobTemplate(
    request: DeleteJobTemplateRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteJobTemplate(
    name: Swift.String,
  ) async throws {
    let request = DeleteJobTemplateRequest().with {
      $0.name = name
    }
    try await self.deleteJobTemplate(request: request)
  }
}
